# Generated by Django 5.0.3 on 2024-05-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='completed_hours',
            new_name='hours_remaining',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='completion_percentage',
            new_name='hours_spent',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='estimated_hours',
        ),
        migrations.AddField(
            model_name='activity',
            name='text_produced',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='activity',
            name='text_remaining',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='project_documents/'),
        ),
    ]
