# Generated by Django 5.0.3 on 2024-05-02 05:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_completed_hours_activity_hours_remaining_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='chief_editors',
            field=models.ManyToManyField(related_name='edited_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='managers',
            field=models.ManyToManyField(related_name='managed_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
