# Generated by Django 5.0.3 on 2024-05-02 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_activity_chief_editors_alter_activity_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='translator',
        ),
        migrations.AddField(
            model_name='activity',
            name='translators',
            field=models.ManyToManyField(related_name='translation_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='chief_editors',
            field=models.ManyToManyField(related_name='edited_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='managers',
            field=models.ManyToManyField(related_name='managed_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
