# Generated by Django 5.0.3 on 2024-05-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='activity',
        ),
        migrations.DeleteModel(
            name='TextEntry',
        ),
        migrations.DeleteModel(
            name='TimeEntry',
        ),
    ]
