# Generated by Django 5.0.3 on 2024-05-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_timeentry_activity_delete_textentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='show_editing',
            field=models.BooleanField(default=False),
        ),
    ]
